export const GET_LIST_DATA = "user/get_list_data"
export const CHANGE_SEARCH_PARAMS = "usr/chang_search_params"
export const CHANGE_LIST_DATA = "user/chang_list_data"
export const CHANGE_INPUT_VALUE = "user/chang_input_value"
export const CHANGE_PAGINATION = "user/change_pagination"
export const CHANGE_VISIBLE = "user/visible"
export const CHANGE_USER_INFO = "user/change_user_info"
